### ISSUE TITLE
SummaryRule reports "Complete" but no resulting Kusto table is created

### ISSUE THREAD

**Issue by matucker-msft** [Azure/adx-mon#732]
I'm running into an issue where my SummaryRule resource appears to be processed successfully based on its status conditions, but I do not see the expected output table created in Azure Data Explorer.

Here's the relevant portion of the status on the resource:

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-05-23T00:50:14Z"
    message: '[]'
    observedGeneration: 1
    reason: Complete
    status: "True"
    type: summaryrule.adx-mon.azure.com/OperationId
  - lastTransitionTime: "2025-05-20T23:50:14Z"
    message: ""
    observedGeneration: 1
    reason: Created
    status: "True"
    type: summaryrule.adx-mon.azure.com
```

So it looks like the controller thinks it has completed the summary operation, but no resulting Kusto table is created in the target database. I've verified that:

The ADX connection is healthy and other rules are working (e.g., ingest rules).

There are no obvious errors in the controller logs.

The query used in the summary rule returns results when run directly in Kusto.

It's like it gets so close to working, but silently stops short of completing the final table creation.

Expected behavior:
A new Kusto table should be created as a result of the SummaryRule.

Actual behavior:
Status reports success, but no new table appears in the database.

Steps to reproduce:
1. Apply a valid SummaryRule CRD.
2. Wait for status.conditions to show Complete.
3. Check Kusto for the resulting summary table — it is missing.
