### ISSUE TITLE
A failing to execute SummaryRule should indiciate such in the CRD status

### ISSUE THREAD

**Issue by matucker-msft** [Azure/adx-mon#769]
I have a SummaryRule that is failing to execute because the query is invalid, but the conditions on the CRD don't indicate that.

I should see that the SummaryRule is failing and the reason for the failure.

```
status:
  conditions:
  - lastTransitionTime: "2025-06-05T16:44:51Z"
    message: '[]'
    observedGeneration: 1
    reason: Complete
    status: "True"
    type: summaryrule.adx-mon.azure.com/OperationId
  - lastTransitionTime: "2025-05-20T23:50:14Z"
    message: ""
    observedGeneration: 1
    reason: Created
    status: "True"
    type: summaryrule.adx-mon.azure.com
```
