### ISSUE TITLE
A failed summary rule is not retried

### ISSUE THREAD

**Issue by matucker-msft** [Azure/adx-mon#807]
A summary rule was incorrectly created with a syntax error, which resulted in it failing. The resulting conditions were:

```
  conditions:
  - lastTransitionTime: "2025-06-20T17:37:01Z"
    message: '[{"operationId":"f7c21fbc-dd18-490e-8132-a83649ecdec5","startTime":"2025-06-20T17:31:00Z","endTime":"2025-06-20T17:36:00Z"}]'
    observedGeneration: 1
    reason: InProgress
    status: Unknown
    type: summaryrule.adx-mon.azure.com/OperationId
  - lastTransitionTime: "2025-06-20T16:03:01Z"
    message: async operation f7c21fbc-dd18-490e-8132-a83649ecdec5 failed
    observedGeneration: 1
    reason: Failed
    status: "False"
    type: summaryrule.adx-mon.azure.com
  - lastTransitionTime: "2025-06-20T16:01:02Z"
    message: "2025-06-20T17:36:00Z"
    observedGeneration: 1
    reason: ExecutionCompleted
    status: "True"
    type: summaryrule.adx-mon.azure.com/LastSuccessfulExecution
```

The query used to check on the async operation status returned the correct results:

```
.show operations | where StartedOn > ago(1d) | where Operation == 'TableSetOrAppend' | summarize arg_max(LastUpdatedOn, OperationId, State, ShouldRetry) by OperationId | project LastUpdatedOn, OperationId = tostring(OperationId), State, ShouldRetry = todouble(ShouldRetry) | sort by LastUpdatedOn asc
| where OperationId == "f7c21fbc-dd18-490e-8132-a83649ecdec5"

LastUpdatedOn	OperationId	State	ShouldRetry
6/20/2025, 5:36:01.6948238 PM	f7c21fbc-dd18-490e-8132-a83649ecdec5	Failed	1
```

I'd expect that the operation should have been retried, especially after the CRD was updated with a new query without the syntax error. But I never see things progress beyond this, because the operation is still in the conditions as InProgress even though it most definitely failed.

I also would expect to see more than "async operation X failed" in the message. I should see the actual syntax error. For example, in this case:

```
.show operations | where OperationId == "f7c21fbc-dd18-490e-8132-a83649ecdec5" | summarize arg_max(LastUpdatedOn, Status)

LastUpdatedOn	Status
6/20/2025, 5:36:01.6948238 PM	Request is invalid and cannot be processed: Semantic error: SEM0001: Filter expression should be Boolean
```
